FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu

RUN install_packages can-utils

ADD humio-log-collector /usr/local/bin/humio-log-collector
ADD config.yaml /etc/humio-log-collector/config.yaml

CMD /usr/local/bin/humio-log-collector -cfg /etc/humio-log-collector/config.yaml
